openapi: 3.0.3
info:
  title: Cheat Buster API
  version: 1.0.0
  description: API to search by email or name.
servers:
  - url: http://localhost:3000/api

paths:
  /search:
    get:
      summary: Search for a user
      parameters:
        - name: email
          in: query
          required: false
          schema:
            type: string
            format: email
        - name: name
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: User found
        '400':
          description: Invalid query
        '404':
          description: No user found
        '500':
          description: Server error
